---
title: "The 2024 NFL season in 10 graphs"
output: html_notebook
---


```{r setup, include=TRUE, warning=FALSE, message=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
    tidyverse,
    nflverse,
    gt,
    gtExtras,
    gtUtils,
    ggfx,
    rvest,
    httr,
    jsonlite,
    patchwork,
    ggtext,
    ggrepel,
    ggimage,
    dlookr,
    showtext,
    sysfonts,
    janitor,
    grid,
    ggiraph,
    glue,
    here
)    

sysfonts::font_add_google("Lexend")
showtext::showtext_auto()
```

```{r nfl_analytics_theme, include=TRUE}
theme_nfl_analytics <- function(..., base_size = 12) {
  theme(
    text = element_text(family = "Lexend", size = base_size, color = "black", face='bold'),
    axis.ticks = element_blank(),
    axis.title = element_text(face = "bold"),
    axis.text = element_text(face = "bold"),
    plot.title.position = "plot",
    plot.title = element_markdown(size = 16, vjust = .02, hjust = 0.5),
    plot.subtitle = element_markdown(hjust = 0.5),
    plot.caption = element_markdown(size = 8),
    panel.grid.minor = element_blank(),
    panel.grid.major =  element_line(color = "#d0d0d0"),
    panel.background = element_rect(fill = "#f7f7f7"),
    plot.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_blank(),
    legend.background = element_rect(color = "#F7F7F7"),
    legend.key = element_rect(color = "#F7F7F7"),
    legend.title = element_text(face = "bold", hjust = .5),
    strip.text = element_text(face = "bold"))
}
```

Potential ideas to explore:

* Benching Richardson
* Arthur Smith play action
* Dolphins: with and without Tua
* Regression of Stroud, Rodgers 
* 2 shell and passing down
* Lions offensive efficiency

* New kickoff
* Vikings defensive consistency 

#### Rookie QBs: performance and inconsistency

* Jayden Daniels spotlight

```{r}
pbp_2024 <- load_pbp(seasons = 2024)
ftn_2024 <- load_ftn_charting(seasons = 2024)

pbp_2024 <- pbp_2024 %>% 
  left_join(x=.,
            y=ftn_2024,
            by=c('game_id' = 'nflverse_game_id',
                 'play_id' = 'nflverse_play_id',
                 'season',
                 'week'))
```

```{r params, include=TRUE}
max_week_param <- pbp_2024 %>% 
  summarise(max(week)) %>% 
  pull()
```

```{r}
pbp_2024 %>% 
  select(contains('epa'))
```


```{r}
(rookie_qb_epa_weekly_2024 <- pbp_2024 %>% 
  filter(passer %in% c('J.Daniels', 'C.Williams', 'B.Nix', 'D.Maye')) %>% 
  group_by(game_id, week, posteam, passer, passer_id) %>% 
  summarise(across(
    c('qb_epa', 'pass_attempt', 'air_epa', 'yac_epa'),
    list(
        mean = ~round(mean(., na.rm = TRUE), 2),
        sum = ~round(sum(., na.rm = TRUE), 2)
      ),
      .names = "{.fn}_{.col}"
    ),
    .groups = 'drop') %>% 
  filter(sum_pass_attempt >= 10))
```

```{r}
rookie_qb_epa_weekly_2024 %>% 
  ggplot(.,
         aes(x=week,
             y=mean_qb_epa,
             color=posteam)) + 
  geom_line(linewidth=1.2) + 
  geom_point(data=. %>% filter(week == max_week_param),
             size=3) + 
  geom_text(data=. %>% filter(week == max_week_param),
            aes(x=week + 1,
                label=passer),
            family='Lexend') + 
  geom_hline(yintercept = 0, color='black', linetype='dashed') + 
  labs(title='EPA per dropback of 1st round rookies in 2024',
       subtitle = glue('Through Week {max_week_param}'),
       caption = 'Source: {nflverse} package<br>Minimum 10 attempts to qualify as a full game',
       x='Week',
       y='EPA/dropback') + 
  theme_nfl_analytics() +
  # theme(legend.position = 'top') + 
  scale_color_nfl(type='secondary')
  # theme(axis.title.y = element_text(angle=0))
```


```{r}
pbp_2024 %>% 
  # filter(passer %in% c('J.Daniels', 'C.Williams', 'B.Nix', 'D.Maye')) %>% 
  filter(!is.na(passer)) %>% 
  group_by(posteam, passer, passer_id) %>% 
  summarise(across(
    c('qb_epa', 'pass_attempt', 'air_epa', 'yac_epa'),
    list(
        mean = ~round(mean(., na.rm = TRUE), 5),
        sum = ~round(sum(., na.rm = TRUE), 5)
      ),
      .names = "{.fn}_{.col}"
    ),
    .groups = 'drop') %>% 
  filter(sum_pass_attempt >= 175) %>% 
  mutate(rank_qb_epa = rank(-mean_qb_epa)) %>% 
  filter(passer %in% c('J.Daniels', 'C.Williams', 'B.Nix', 'D.Maye')) %>%
  ggplot(.,
         aes(y=reorder(passer_id, mean_qb_epa),
             x=mean_qb_epa)) + 
  geom_col(aes(fill = if_else(mean_qb_epa >= 0,
                              '#81fd02', '#8f55e5')),
           width = 0.1) + 
  ggrepel::geom_text_repel(aes(x=mean_qb_epa,
                               label = glue('NFL rank: {rank_qb_epa}')), 
                           family='Lexend') + 
  labs(y='',
       x='EPA per dropback',
       title='EPA per dropback among rookie 1st-rounders in 2024', 
       subtitle=glue('Through Week {max_week_param}'), 
       caption='Source: {nflverse} package<br>Minimum 175 attempts') + 
  theme_nfl_analytics() + 
  theme(legend.position = 'none',
        axis.text.y = nflplotR::element_nfl_headshot(size = 3))
```

#### Kickoff eval

```{r}
kickoff_99_24 <- load_pbp(seasons = TRUE) %>% 
  filter(play_type == 'kickoff',
         season_type == 'REG')



return_yards
kick_distance
touchback
kickoff_attempt
kickoff_inside_twenty
kickoff_in_endzone
kickoff_fair_catch
touchdown
season
```



