---
title: "Calculating EPA League-wide"
output: html_document
---

```{r libraries, include=TRUE, warning=FALSE, message=FALSE}
pacman::p_load(
    tidyverse,
    nflverse,
    gt,
    gtExtras,
    gtUtils,
    ggtext,
    ggrepel,
    patchwork,
    ggimage,
    showtext,
    janitor,
    scales,
    glue,
    here
)    
```

```{r theme_nfl_analytics, include=TRUE}
theme_nfl_analytics <- function(..., base_size = 12) {
  
  theme(
    text = element_text(family = "Lexend",
                        size = base_size,
                        color = "black"),
    axis.ticks = element_blank(),
    axis.title = element_text(face = "bold"),
    axis.text = element_text(face = "bold"),
    plot.title.position = "plot",
    plot.title = element_markdown(size = 16,
                                  vjust = .02,
                                  hjust = 0.5),
    plot.subtitle = element_markdown(hjust = 0.5),
    plot.caption = element_markdown(size = 8),
    panel.grid.minor = element_blank(),
    panel.grid.major =  element_line(color = "#d0d0d0"),
    panel.background = element_rect(fill = "#f7f7f7"),
    plot.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_blank(),
    legend.background = element_rect(color = "#F7F7F7"),
    legend.key = element_rect(color = "#F7F7F7"),
    legend.title = element_text(face = "bold"),
    legend.title.align = 0.5,
    strip.text = element_text(face = "bold"))
}
```

# Data

```{r play_by_play, include=TRUE}
play_by_play <- nflreadr::load_pbp(seasons = 2000:2024)
```

# Expected Points

To do:

*  This doesn't yet take into account what the opponent does on their *next* drive, which seems to be what expected points is doing.
*  I am using `geom_smooth()` to create a loess model, but I could fit a GAM to the data (distance to endzone stratified by down). I think that expected points is a model-based estimate.

```{r}
scoring_tibble <- c('Punt' = 0,
                    'Touchdown' = 6,
                    'Turnover' = 0,
                    'Field goal' = 3,
                    'Turnover on downs' = 0,
                    'End of half' = 0,
                    'Missed field goal' = 0,
                    'Opp touchdown' = -6,
                    'Safety' = -2)
```


```{r expected_points, include=TRUE}
expected_points <- play_by_play %>% 
  filter(!is.na(down)) %>%
  mutate(points_drive = scoring_tibble[fixed_drive_result] %||% NA_integer_) %>% 
  # filter(!is.na(down), !is.na(yardline_100), !is.na(points_drive))
  group_by(down, yardline_100) %>% 
  summarise(expected_points = mean(points_drive, na.rm = TRUE),
            .groups = 'drop')
```

```{r}
expected_points %>% 
  ggplot(.,
         aes(x=yardline_100,
             y=expected_points,
             group=as.factor(down),
             color=as.factor(down))) +
  # geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE, span = 0.4) + 
  labs(x="Yards from Opponent's End Zone",
       y='Expected Points') + 
  theme_nfl_analytics()
```


