---
title: "Defensive Advanced Stats: EPA per play vs Success Rate"
output: html_document
---

```{r setup, include=TRUE, warning=FALSE, message=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
    tidyverse,
    nflverse,
    gt,
    gtExtras,
    gtUtils,
    ggfx,
    rvest,
    httr,
    jsonlite,
    patchwork,
    ggtext,
    ggrepel,
    ggimage,
    dlookr,
    showtext,
    sysfonts,
    janitor,
    grid,
    ggiraph,
    glue,
    here
)    

sysfonts::font_add_google("Lexend")
showtext::showtext_auto()
```

```{r nfl_analytics_theme, include=TRUE}
nfl_analytics_theme <- function(..., base_size = 12) {
  theme(
    text = element_text(family = "Lexend", size = base_size, color = "black"),
    axis.ticks = element_blank(),
    axis.title = element_text(face = "bold"),
    axis.text = element_text(face = "bold"),
    plot.title.position = "plot",
    plot.title = element_markdown(size = 16, vjust = .02, hjust = 0.5),
    plot.subtitle = element_markdown(hjust = 0.5),
    plot.caption = element_markdown(size = 8),
    panel.grid.minor = element_blank(),
    panel.grid.major =  element_line(color = "#d0d0d0"),
    panel.background = element_rect(fill = "#f7f7f7"),
    plot.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_blank(),
    legend.background = element_rect(color = "#F7F7F7"),
    legend.key = element_rect(color = "#F7F7F7"),
    legend.title = element_text(face = "bold", hjust = .5),
    strip.text = element_text(face = "bold"))
}
```

```{r teams, include=TRUE}
teams <- nflreadr::load_teams(current = TRUE)
```

```{r play_by_play_2024, include=TRUE}
play_by_play_2024 <- load_pbp(seasons = most_recent_season())
```

```{r defensive_epa_success, include=TRUE}
defensive_epa_success <- play_by_play_2024 %>% 
  filter(special != 1,
         # this removes no play situations resulting from penalties
         play_type %in% c('run', 'pass')) %>% 
  group_by(defteam) %>%
  summarise(sum_epa = sum(epa, na.rm = TRUE),
            plays = n(),
            def_success = 1 - mean(success, na.rm = TRUE), 
            .groups = 'drop') %>% 
  mutate(epa_per_play = sum_epa / plays,
         rank_epa_per_play = rank(epa_per_play),
         rank_def_success = rank(-def_success)) %>% 
  arrange(epa_per_play)
```

```{r turnovers, include=TRUE}
# Turnovers can happen on special teams and other play types, so the above filter misses those
# I'm still missing something in the logic, according to footballdb.com the Vikings have 15 after 7 games, not 16
turnovers <- play_by_play_2024 %>% 
  filter(!is.na(defteam)) %>% 
  group_by(defteam) %>% 
  summarise(interceptions = sum(interception, na.rm = TRUE),
            fumbles = sum(fumble_lost, na.rm = TRUE),
            .groups = 'drop') %>% 
  mutate(ttl_turnovers = interceptions + fumbles) %>% 
  arrange(-ttl_turnovers)
```

```{r defensive_epa_success_join_teams, include=TRUE}
(defensive_epa_success <- defensive_epa_success %>% 
  left_join(x=.,
            y=teams,
            by=c('defteam' = 'team_abbr')))
```


```{r defensive_epa_success_plot, include=TRUE}
defensive_epa_success %>% 
  ggplot(.,
         aes(x=def_success,
             y=epa_per_play)) + 
  geom_mean_lines(aes(x0=def_success,
                      y0=epa_per_play),
                  color='black', linewidth=.8, linetype='dashed') + 
  geom_smooth(method=lm, se=FALSE) + 
  geom_image(aes(image = team_logo_wikipedia), size=.1) +
  scale_x_continuous(breaks = scales::pretty_breaks(),
                     labels = scales::percent_format()) +
  scale_y_continuous(breaks = scales::pretty_breaks(),
                     transform = 'reverse') +
  labs(title='Defensive EPA per play vs. Defensive success rate',
       y='EPA per play',
       x='Success Rate') + 
  nfl_analytics_theme()
```







#### Pass Rush

```{r}
pbp_22_24 <- load_pbp(seasons = 2022:2024) %>% 
  filter(season_type == 'REG')

ftn_22_24 <- load_ftn_charting(seasons = 2022:2024)

pbp_22_24 <- pbp_22_24 %>% 
  left_join(x=.,
            y=ftn_22_24,
            by=c('game_id' = 'nflverse_game_id',
                 'play_id' = 'nflverse_play_id',
                 'season',
                 'week'))

# n_blitzer
```

```{r}
(df_pass_rush <- pbp_22_24 %>% 
  filter(play_type == 'pass') %>% 
  group_by(season, n_pass_rushers) %>% 
  summarise(plays = n(),
            sack = sum(sack, na.rm = TRUE),
            interception = sum(interception, na.rm = TRUE),
            pass_attempt = sum(pass_attempt, na.rm = TRUE), 
            .groups = 'drop') %>% 
  mutate(across(c('sack', 'interception'),
                list(
                  rate = ~round(. / plays, 3)
                ),
                .names = '{.col}_{.fn}'))
)
```

```{r}
pbp_22_24 %>% 
  filter(play_type %in% c('punt', 'kickoff', 'field_goal', 'extra_point')) %>% 
  group_by(season, posteam, play_type) %>% 
  summarise(ttl_epa = sum(epa, na.rm = TRUE),
            epa_per_play = mean(epa, na.rm = TRUE),
            .groups = 'drop') %>% 
  filter(season == 2024) %>% 
  arrange(-epa_per_play)

pbp_22_24 %>% 
  filter(play_type %in% c('punt', 'kickoff', 'field_goal', 'extra_point')) %>% 
  group_by(season, defteam, play_type) %>% 
  summarise(ttl_epa = sum(epa, na.rm = TRUE),
            epa_per_play = mean(epa, na.rm = TRUE),
            .groups = 'drop') %>% 
  filter(season == 2024) %>% 
  arrange(epa_per_play)

df_pass_rush %>% 
  filter(n_pass_rushers > 2 & n_pass_rushers < 8) %>% 
  ggplot(.,
         aes(x=n_pass_rushers,
             y=interception_rate)) + 
  geom_col() + 
  facet_wrap(~season,
             ncol = 1) + 
  theme_nfl_analytics()
```

```{r}
pbp_2024 %>% 
  # filter(fumble_lost == 1)
  # select(contains('fumbl'))
  group_by(defteam, week) %>% 
  summarise(fumble_recovery = sum(fumble_lost, na.rm = TRUE),
            interception = sum(interception, na.rm = TRUE),
            .groups = 'drop') %>% 
  mutate(takeaways = fumble_recovery + interception) %>% 
  arrange(-takeaways)

pbp_2024 %>% 
  group_by(posteam, week) %>% 
  summarise(explosive_runs = sum(yards_gained[play_type == 'run'] >= 10, na.rm = TRUE),
            explosive_passes = sum(yards_gained[play_type == 'pass'] >= 20, na.rm = TRUE),
            .groups = 'drop')
```

```{r}
pbp_2024 %>% 
  # filter(fumble_lost == 1)
  # select(contains('fumbl'))
  group_by(posteam, defteam, week) %>% 
  summarise(fumble_recovery = sum(fumble_lost, na.rm = TRUE),
            interception = sum(interception, na.rm = TRUE),
            explosive_runs = sum(yards_gained[play_type == 'run'] >= 10, na.rm = TRUE),
            explosive_passes = sum(yards_gained[play_type == 'pass'] >= 20, na.rm = TRUE),
            .groups = 'drop') %>% 
  mutate(takeaways = fumble_recovery + interception) %>% 
  filter((posteam == 'DAL' | posteam == 'DET') & (defteam == 'DAL' | defteam == 'DET'))
```


