---
title: "NFL Analytics: a review of Expected Points Added"
output: html_document
---


```{r setup, include=TRUE, warning=FALSE, message=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
    tidyverse,
    nflverse,
    gt,
    gtExtras,
    gtUtils,
    ggfx,
    rvest,
    httr,
    jsonlite,
    patchwork,
    ggtext,
    ggrepel,
    ggimage,
    dlookr,
    showtext,
    sysfonts,
    janitor,
    grid,
    ggiraph,
    glue,
    here
)    

sysfonts::font_add_google("Lexend")
showtext::showtext_auto()
```

```{r theme_nfl_analytics, include=TRUE}
theme_nfl_analytics <- function(..., base_size = 12) {
  theme(
    text = element_text(family = "Lexend", size = base_size, color = "black"),
    axis.ticks = element_blank(),
    axis.title = element_text(face = "bold"),
    axis.text = element_text(face = "bold"),
    plot.title.position = "plot",
    plot.title = element_markdown(size = 16, vjust = .02, hjust = 0.5),
    plot.subtitle = element_markdown(hjust = 0.5),
    plot.caption = element_markdown(size = 8),
    panel.grid.minor = element_blank(),
    panel.grid.major =  element_line(color = "#d0d0d0"),
    panel.background = element_rect(fill = "#f7f7f7"),
    plot.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_blank(),
    legend.background = element_rect(color = "#F7F7F7"),
    legend.key = element_rect(color = "#F7F7F7"),
    legend.title = element_text(face = "bold", hjust = .5),
    strip.text = element_text(face = "bold"))
}
```

```{r teams, include=FALSE}
# teams <- nflreadr::load_teams(current = TRUE)
```


This looks like a good article on [EPA](https://bestballstats.com/expected-points-added-a-full-explanation/#:~:text=Expected%20Points%20Added%20(EPA)%20is,evaluate%20team%20and%20player%20performance.) and [another](https://www.actionnetwork.com/education/what-is-epa-how-expected-points-added-advanced-metric-can-help-you-with-football-betting).


```{r play_by_play_2024, include=TRUE}
play_by_play_2024 <- load_pbp(seasons=most_recent_season())
```

```{r week_max_param, include=TRUE}
week_max_param <- play_by_play_2024 %>% summarise(max(week)) %>% pull()
```

# Offensive EPA 

```{r team_offensive_epa, include=TRUE}
(team_offensive_epa <- play_by_play_2024 %>% 
  filter(play_type %in% c('run', 'pass')) %>% 
  group_by(posteam) %>% 
  filter(!is.na(posteam)) %>% 
  summarise(avg_offensive_epa = mean(epa, na.rm = TRUE),
            .groups = 'drop') %>% 
  rename(team = posteam))
```

```{r team_defensive_epa, include=TRUE}
(team_defensive_epa <- play_by_play_2024 %>% 
  filter(play_type %in% c('run', 'pass')) %>% 
  group_by(defteam) %>% 
  filter(!is.na(posteam)) %>% 
  summarise(avg_defensive_epa = mean(epa, na.rm = TRUE),
            .groups = 'drop') %>% 
  rename(team = defteam))
```

```{r df_team_epa, include=TRUE}
(df_team_epa <- team_offensive_epa %>% 
  left_join(x=.,
            y=team_defensive_epa,
            by='team'))
  # left_join(x=.,
  #           y=teams,
  #           by=c('team' = 'team_abbr')))
```


From here, I'm borrowing some design concepts from [The F5 Substack](https://thef5.substack.com/p/how-to-diamond-plots-in-r) to make this plot more readable.

```{r}
# find the max absolute value of off/def epa for our plot
sort(abs(c(max(df_team_epa$avg_offensive_epa), max(df_team_epa$avg_defensive_epa), min(df_team_epa$avg_offensive_epa), min(df_team_epa$avg_defensive_epa))), decreasing = T)
```

```{r}
# set max and min for off and def epa (want them to be symmetric for chart)
off_epa_min <- -.25
off_epa_max <- .25
def_epa_min <- -.25
def_epa_max <- .25
```

```{r fig.height=7, fig.width=7, warning=FALSE, include=TRUE}
(epa_per_play_plot <- df_team_epa %>% 
  ggplot(.,
         aes(x=avg_offensive_epa,
             y=avg_defensive_epa)) + 
  annotate("rect", 
           xmin = 0, xmax = off_epa_max, ymin = def_epa_min, ymax = 0, 
           fill= "#a6dba0", alpha = .5) +
  annotate("rect", 
           xmin = off_epa_min, xmax = 0, ymin = 0, ymax = def_epa_max, 
           fill= "#c2a5cf", alpha = .5) +
  # also copied -- I will break down a better way
  # hack together a few chart guides (ie, 'Good D, Bad D')
  geom_richtext(aes(x = .2, y = .2, label = "Good O, Bad D"), 
                size = 2.75, fontface = 'bold', color = 'black', fill = "#f7f7f7") +
  geom_richtext(aes(x = -.2, y = -.2, label = "Bad O, Good D"), 
                size = 2.75, fontface = 'bold', color = 'black', fill = "#f7f7f7") +
  geom_richtext(aes(x = -.2, y = .2, label = "Bad O, Bad D"), 
                size = 2.75, fontface = 'bold', color = 'white',  fill = "#762a83", label.colour = 'black') +
  geom_richtext(aes(x = .195, y = -.2, label = "Good O, Good D"), 
                size = 2.75, fontface = 'bold', color = 'white', fill = "#1b7837", label.colour = 'black') +
  # note: I've been using geom_image(), but this appears to not have a transparent background which geom_nfl_logos() offers
  geom_nfl_logos(aes(team_abbr = team), width = 0.09, alpha = 0.75) +
  scale_y_continuous(breaks = seq(-.25, .25, .05),
                     transform = 'reverse') + 
  scale_x_continuous(breaks = seq(-.25, .25, .05)) + 
  labs(
    title = '**Expected Points Added per Play**: Offense vs. Defense',
    subtitle = glue::glue('2024 season, through Week {week_max_param}'),
    x = "Offensive EPA/play",
    y = "Defensive EPA/play"
    # caption = 'Source: {nflreadr} package<br>Inspo: *The F5 Newsletter* &<br>*Introduction to NFL Analytics with R*'
    ) +
  theme_nfl_analytics() + 
  theme(legend.position = 'none'))
```

```{r}
play_by_play_2024 %>% 
  filter(!is.na(posteam)) %>% 
  group_by(posteam) %>% 
  summarise(avg_epa_per_play = mean(epa, na.rm = TRUE),
            .groups = 'drop') %>% 
  ggplot(.,
         aes(x = avg_epa_per_play,
             y = reorder(posteam, avg_epa_per_play))) +
  geom_col(aes(fill = if_else(avg_epa_per_play >= 0,
                              "#2c7bb6", "#d7181c")),
           width = 0.2) +
  geom_vline(xintercept = 0, color = "black") +
  scale_fill_identity() +
  geom_nfl_logos(aes(team_abbr = posteam), width = 0.03) +
  labs(x='EPA per Play',
       y='',
       title = "**Offensive Expected Points Added per Play**",
       subtitle = glue::glue("2024 Regular Season, through Week {week_max_param}"),
       caption = "*Inspired by An Introduction to NFL Analytics with R*") + 
  scale_x_continuous(breaks = scales::pretty_breaks(n = 6)) +
  scale_y_discrete(expand = c(.05, 0)) +
  theme_nfl_analytics() +
  theme(axis.text.y = element_blank())
```


```{r}
play_by_play_2024 %>% 
  filter(!is.na(posteam)) %>% 
  group_by(defteam) %>% 
  summarise(avg_epa_per_play = mean(epa, na.rm = TRUE),
            .groups = 'drop') %>% 
  ggplot(.,
         aes(x = avg_epa_per_play,
             y = reorder(defteam, -avg_epa_per_play))) +
  geom_col(aes(fill = if_else(avg_epa_per_play >= 0,
                              "#d7181c", "#2c7bb6")),
           width = 0.2) +
  geom_vline(xintercept = 0, color = "black") +
  scale_fill_identity() +
  geom_nfl_logos(aes(team_abbr = defteam), width = 0.03) +
  labs(x='EPA per Play',
       y='',
       title = "**Defensive Expected Points Added per Play**",
       subtitle = glue::glue("2024 Regular Season, through Week {week_max_param}"),
       caption = "*Inspired by An Introduction to NFL Analytics with R*") + 
  scale_x_continuous(breaks = scales::pretty_breaks(n = 6),
                     transform = 'reverse') +
  scale_y_discrete(expand = c(.05, 0)) +
  theme_nfl_analytics() +
  theme(axis.text.y = element_blank())
```

```{r run_pass_def_epa, include=TRUE}
run_pass_def_epa <- play_by_play_2024 %>% 
  filter(play_type %in% c('run', 'pass')) %>% 
  group_by(defteam, play_type) %>% 
  summarise(avg_epa = mean(epa, na.rm = TRUE),
            .groups = 'drop') %>% 
  pivot_wider(names_from = play_type, values_from = avg_epa)
```

```{r}
# find the max absolute value of off/def epa for our plot
sort(abs(c(max(run_pass_def_epa$pass), max(run_pass_def_epa$run), min(run_pass_def_epa$pass), min(run_pass_def_epa$run))), decreasing = T)
```

```{r}
# set max and min for off and def epa (want them to be symmetric for chart)
def_run_epa_min <- -.35
def_run_epa_max <- .35
def_pass_epa_min <- -.35
def_pass_epa_max <- .35
```

```{r defensive_epa_runpass, fig.width=7, fig.height=7, warning=FALSE, include=TRUE}
(defensive_epa_runpass <-  run_pass_def_epa %>% 
  ggplot(.,
         aes(x=run,
             y=pass)) + 
  annotate("rect", 
              xmin = 0, xmax = def_run_epa_min, ymin = def_pass_epa_min, ymax = 0, 
              fill= "#a6dba0", alpha = .5, color = 'transparent') +
  annotate("rect", 
           xmin = def_run_epa_max, xmax = 0, ymin = 0, ymax = def_pass_epa_max, 
           fill= "#c2a5cf", alpha = .5, color = 'transparent') +
  geom_richtext(aes(x = .25, y = .25, label = "Bad P, Bad R"), 
                size = 2.75, fontface = 'bold', color = 'white', fill = "#762a83") +
  geom_richtext(aes(x = -.245, y = -.25, label = "Good P, Good R"), 
                size = 2.75, fontface = 'bold', color = 'white', fill = "#1b7837") +
  geom_richtext(aes(x = -.25, y = .25, label = "Bad P, Good R"), 
                size = 2.75, fontface = 'bold', color = 'black',  fill = "#f7f7f7", label.colour = 'black') +
  geom_richtext(aes(x = .25, y = -.25, label = "Good P, Bad R"), 
                size = 2.75, fontface = 'bold', color = 'black', fill = "#f7f7f7", label.colour = 'black') +
  # note: I've been using geom_image(), but this appears to not have a transparent background which geom_nfl_logos() offers
  geom_nfl_logos(aes(team_abbr = defteam), width = 0.09, alpha = 0.75) +
  scale_x_continuous(breaks = scales::pretty_breaks(),
                     limits = c(.3, -.3),
                     transform = 'reverse') +
  scale_y_continuous(breaks = scales::pretty_breaks(),
                     limits = c(.3, -.3),
                     transform = 'reverse') +
  labs(x='Against the Run',
       y='Against the Pass',
       caption='Source: {nflreadr} package') + 
  ggtitle('**Average Defensive Expected Points Added**: Run vs. Pass',
          subtitle = glue::glue('2024 season (through Week {week_max_param})')) + 
  theme_nfl_analytics() + 
  theme(legend.position = 'none'))
```

```{r ftn_charting_2024, include=TRUE}
ftn_charting_2024 <- load_ftn_charting(seasons = most_recent_season())
```

```{r pbp_plus_ftn_2024, include=TRUE}
pbp_plus_ftn_2024 <- play_by_play_2024 %>% 
  left_join(x=.,
            y=ftn_charting_2024,
            by=c('game_id' = 'nflverse_game_id',
                 'play_id' = 'nflverse_play_id'))
```


```{r}
passing_epa <- pbp_plus_ftn_2024 %>% 
  filter(!is.na(passer)) %>% 
  group_by(passer, posteam) %>% 
  summarise(plays = n(),
            count_drops = sum(is_drop, na.rm = TRUE),
            interceptions = sum(interception, na.rm = TRUE),
            sum_qb_epa = sum(qb_epa, na.rm = TRUE),
            sum_qb_epa_drops = sum(qb_epa[is_drop == TRUE], na.rm = TRUE),
            sum_qb_epa_int = sum(qb_epa[interception == 1], na.rm = TRUE),
            sum_qb_epa_sack = sum(qb_epa[sack == 1], na.rm = TRUE),
            sum_qb_epa_incomplete = sum(qb_epa[incomplete_pass == 1], na.rm = TRUE),
            sum_qb_epa_dpi = sum(qb_epa[penalty_type == 'Defensive Pass Interference'], na.rm = TRUE),
            .groups = 'drop') %>% 
  filter(plays >= 25) %>% 
  mutate(
    across(
      starts_with("sum"),
      list(
        # mean = ~round(mean(., na.rm = TRUE), 2),
        # zscore = ~scale(.),
        mean_centered = ~. - mean(., na.rm = TRUE)
      ),
      .names = "{.fn}_{.col}"
    )) %>% 
  arrange(-sum_qb_epa_int)
```


```{r qb_epa_mean_centered_gt, include=TRUE, warning=FALSE, results='asis'}
passing_epa %>% 
  select(passer, posteam, plays, contains('mean_centered'), -mean_centered_sum_qb_epa_incomplete) %>% 
  arrange(-mean_centered_sum_qb_epa) %>% 
  gt() %>% 
  cols_label(passer = 'Name',
             posteam = 'Team',
             plays = 'Plays',
             mean_centered_sum_qb_epa = 'EPA',
             mean_centered_sum_qb_epa_drops = 'Drops',
             mean_centered_sum_qb_epa_int = 'INTs',
             mean_centered_sum_qb_epa_sack = 'Sacks',
             mean_centered_sum_qb_epa_dpi = 'DPI')
```



# QB EPA Tables 


```{r gt_epa_per_play, include=FALSE, warning=FALSE, results='asis'}
pbp_plus_ftn_2024 %>% 
  filter(!is.na(passer)) %>% 
  group_by(passer, posteam) %>% 
  summarise(sum_qb_epa = sum(qb_epa, na.rm = TRUE),
            sum_comp_yac_epa = sum(comp_yac_epa, na.rm = TRUE),
            plays = n(),
            .groups = 'drop') %>% 
  filter(plays >= 100) %>% 
  mutate(epa_per_play = round(sum_qb_epa / plays, 3),
         rank_epa_per_play = rank(-epa_per_play)) %>% 
  arrange(-epa_per_play) %>% 
  gt() %>% 
  cols_label(passer = 'Name',
             posteam = 'Team',
             sum_qb_epa = 'Total EPA',
             sum_comp_yac_epa = 'EPA from YAC (completions only)',
             plays = 'Plays',
             epa_per_play = 'EPA / Play',
             rank_epa_per_play = 'Rank') %>% 
  gt_color_pills(sum_qb_epa, digits = 3) %>% 
  gt_color_pills(sum_comp_yac_epa, digits = 3) %>% 
  gt_color_pills(plays, digits = 0) %>% 
  gt_color_pills(epa_per_play, digits = 3) %>% 
  tab_header(
    title = "Advanced Passing Stats: 2024 Season through Week 7",
    subtitle = "Sorted by Expected Points Added (EPA) per play. Minimum 100 plays."
  ) %>% 
  gt_theme_athletic() %>%
  cols_width(everything() ~ px(120)) %>% 
  gt_border_bars_top("#1c2632", bar_height = 5) %>%
  gt_border_bars_bottom("#1c2632", bar_height = 25, text = "Source: `nflreadr::` package. Inspiration: Georgios Karamanis' Tidy Tuesday work.", text_weight = "normal", text_size = 12)


qb_epa_mean_centered_gt <- htmltools::withTags({passing_epa %>% 
  select(passer, posteam, plays, contains('mean_centered'), -mean_centered_sum_qb_epa_incomplete) %>% 
  arrange(-mean_centered_sum_qb_epa) %>% 
  gt() %>% 
  cols_label(passer = 'Name',
             posteam = 'Team',
             plays = 'Plays',
             mean_centered_sum_qb_epa = 'EPA',
             mean_centered_sum_qb_epa_drops = 'Drops',
             mean_centered_sum_qb_epa_int = 'INTs',
             mean_centered_sum_qb_epa_sack = 'Sacks',
             mean_centered_sum_qb_epa_dpi = 'DPI') %>% 
  gt_color_pills(mean_centered_sum_qb_epa, digits = 3) %>% 
  gt_color_pills(mean_centered_sum_qb_epa_drops, digits = 3) %>% 
  gt_color_pills(mean_centered_sum_qb_epa_int, digits = 3) %>% 
  gt_color_pills(mean_centered_sum_qb_epa_sack, digits = 3) %>% 
  gt_color_pills(mean_centered_sum_qb_epa_dpi, digits = 3) %>% 
  tab_header(
    title = "Advanced Passing Stats: 2024 Season through Week 7",
    subtitle = "All values relative to the average QB in 2024. Minimum 25 plays."
  ) %>% 
  gt_theme_athletic() %>%
  cols_width(everything() ~ px(120)) %>% 
  gt_border_bars_top("#1c2632", bar_height = 5) %>%
  gt_border_bars_bottom("#1c2632", bar_height = 25, text = "Source: `nflreadr::` package. Inspiration: Unexpected Points Substack.", text_weight = "normal", text_size = 12)
  })


```

```{r render_qb_epa_mean_centered_gt, include=TRUE}
qb_epa_mean_centered_gt
```





