---
title: "NFL Analytics: Exploring personnel groupings"
output: html_notebook
---


```{r libraries, include=TRUE, warning=FALSE, message=FALSE}
library(tidyverse)
library(nflverse)
library(gt)
library(ggtext)
library(ggrepel)
library(patchwork)
```

```{r nfl_analytics_theme, include=TRUE}
nfl_analytics_theme <- function(..., base_size = 12) {
  
  theme(
    text = element_text(family = "Lexend",
                        size = base_size,
                        color = "black"),
    axis.ticks = element_blank(),
    axis.title = element_text(face = "bold"),
    axis.text = element_text(face = "bold"),
    plot.title.position = "plot",
    plot.title = element_markdown(size = 16,
                                  vjust = .02,
                                  hjust = 0.5),
    plot.subtitle = element_markdown(hjust = 0.5),
    plot.caption = element_markdown(size = 8),
    panel.grid.minor = element_blank(),
    panel.grid.major =  element_line(color = "#d0d0d0"),
    panel.background = element_rect(fill = "#f7f7f7"),
    plot.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_blank(),
    legend.background = element_rect(color = "#F7F7F7"),
    legend.key = element_rect(color = "#F7F7F7"),
    legend.title = element_text(face = "bold"),
    legend.title.align = 0.5,
    strip.text = element_text(face = "bold"))
}
```

```{r teams, include=TRUE}
teams <- nflreadr::load_teams()
```

### Snap counts 

I'd like to replicate that Pickens was used in 59% of snaps against the Cowboys in Week 5.

```{r snap_counts, include=TRUE}
snap_counts <- load_snap_counts(seasons = most_recent_season())

snap_counts <- snap_counts %>% 
  left_join(x=.,
            y=teams,
            by=c('team' = 'team_abbr'))
```

```{r}
snap_counts %>% 
  filter(player == 'George Pickens') %>% 
  ggplot(.,
         aes(x=week,
             y=offense_pct)) + 
  geom_col(fill='#FFB612') + 
  geom_text(aes(label = paste(100*offense_pct, '%', sep='')), 
            color='black', family='Roboto', fontface='bold', size=5) + 
  ggtitle('**George Pickens** week-to-week snap counts: 2024 NFL Season') + 
  labs(y='% of Offensive Snaps Played',
       x='Week') + 
  scale_y_continuous(labels = scales::percent) + 
  nfl_analytics_theme()
```

## Roman Wilson 

```{r}
snap_counts %>% 
  filter(player == 'Roman Wilson') %>% 
  ggplot(.,
         aes(x=week,
             y=offense_snaps)) + 
  geom_col(fill='#FFB612') + 
  geom_text(aes(label = paste(100*offense_pct, '%', sep='')), 
            color='black', family='Roboto', fontface='bold', size=5) + 
  ggtitle('**Roman Wilson** week-to-week snap counts: 2024 NFL Season') + 
  labs(y='# of Offensive Snaps Played',
       x='Week') + 
  scale_x_continuous(limits = c(0,7)) + 
  # scale_y_continuous(labels = scales::percent) + 
  nfl_analytics_theme()
```


```{r}
snap_counts %>% 
  filter(team == 'PIT',
         position %in% c('T', 'G', 'C',
                         'QB', 'RB', 'WR')) %>% 
  group_by(player) %>% 
  mutate(games_played = n()) %>% 
  filter(games_played >= 6) %>% 
  ggplot(.,
         aes(x=offense_pct,
             y=player)) +
  geom_jitter()
```


# Personnel groupings in 2023

It appears that I can't get personnel groupings for the current season from `load_participation()`.

```{r personnel, include=TRUE}
(personnel <- nflreadr::load_participation(seasons = 2023, include_pbp = TRUE))
```



```{r}
personnel %>% 
  filter(possession_team == 'PIT',
         play_type == 'run',
         rusher %in% c('J.Warren', 'N.Harris')) %>% 
  group_by(defenders_in_box, rusher) %>% 
  summarise(carries = n(),
            yards = sum(yards_gained, na.rm = TRUE),
            .groups = 'drop') %>% 
  mutate(yards_per_carry = round(yards / carries, 1)) %>% 
  filter(defenders_in_box %in% seq(5,8, by=1)) %>% 
  ggplot(.,
         aes(x=yards_per_carry,
             y=defenders_in_box,
             color=rusher)) + 
  geom_jitter(width=0, height = .1) + 
  nfl_analytics_theme() + 
  theme(legend.position = 'top')
```


## Analysis of the three-edge look (Watt, Highsmith, Herbig) 




# From Congelio book

```{r participation, include=TRUE}
(participation <- nflreadr::load_participation(season = 2024, include_pbp = TRUE))
```


```{r participation_split, include=TRUE}
(participation_split <- participation %>%
  filter(!is.na(offense_formation)) %>%
  filter(posteam == "PIT") %>%
  tidyr::separate_rows(offense_players, sep = ";") %>%
  group_by(offense_personnel, offense_players) %>%
  summarize(total = n(),
            .groups = 'drop'))
```

```{r roster_2023, include=TRUE}
roster_2023 <- nflreadr::load_rosters(2023) %>%
  select(full_name, gsis_id, headshot_url)
```


```{r}
participation_split <- participation_split %>%
  left_join(roster_2023, by = c("offense_players" = "gsis_id"))
participation_split
```