---
title: "NFL Analytics: top high-leverage plays"
output: html_notebook
---

```{r libraries, include=TRUE, warning=FALSE, message=FALSE}
pacman::p_load(
    tidyverse,
    nflverse,
    gt,
    gtExtras,
    gtUtils,
    ggtext,
    ggrepel,
    patchwork,
    ggimage,
    showtext,
    janitor,
    scales,
    glue,
    here
)    
```

```{r theme_nfl_analytics, include=TRUE}
theme_nfl_analytics <- function(..., base_size = 12) {
  
  theme(
    text = element_text(family = "Lexend",
                        size = base_size,
                        color = "black"),
    axis.ticks = element_blank(),
    axis.title = element_text(face = "bold"),
    axis.text = element_text(face = "bold"),
    plot.title.position = "plot",
    plot.title = element_markdown(size = 16,
                                  vjust = .02,
                                  hjust = 0.5),
    plot.subtitle = element_markdown(hjust = 0.5),
    plot.caption = element_markdown(size = 8),
    panel.grid.minor = element_blank(),
    panel.grid.major =  element_line(color = "#d0d0d0"),
    panel.background = element_rect(fill = "#f7f7f7"),
    plot.background = element_rect(fill = "#f7f7f7"),
    panel.border = element_blank(),
    legend.background = element_rect(color = "#F7F7F7"),
    legend.key = element_rect(color = "#F7F7F7"),
    legend.title = element_text(face = "bold"),
    legend.title.align = 0.5,
    strip.text = element_text(face = "bold"))
}
```

```{r teams, include=TRUE}
teams <- nflreadr::load_teams(current = TRUE)
```

```{r player_ids, include=TRUE}
player_ids <- nflreadr::load_ff_playerids() %>% 
  filter(db_season == 2024) %>% 
  select(gsis_id, pfr_id) %>% 
  rename(player_id = gsis_id,
         pfr_player_id = pfr_id) %>% 
  filter(complete.cases(.))
# nflreadr::dictionary_ff_playerids
```

# Data

```{r play_by_play_2024, include=TRUE}
play_by_play_2025 <- nflreadr::load_pbp(seasons = most_recent_season())
```

```{r week, include=TRUE}
week <- play_by_play_2025 %>% 
  summarise(max(week)) %>% 
  pull()
```


```{r max_min_epa, include=TRUE, echo=FALSE}
max_epa <- play_by_play_2025 %>% 
  summarise(max(epa, na.rm = TRUE)) %>% 
  pull()

min_epa <- play_by_play_2024 %>% 
  summarise(min(epa, na.rm = TRUE)) %>% 
  pull()
```

```{r top_plays, include=TRUE}
top_plays <- play_by_play_2025 %>% 
  filter(str_detect(game_id, 'PIT')) %>% 
  left_join(x=.,
            y=teams %>% select(team_abbr, team_wordmark),
            by=c('posteam' = 'team_abbr')) %>% 
  left_join(x=.,
            y=teams %>% select(team_abbr, home_nick = team_nick),
            by=c('home_team' = 'team_abbr')) %>% 
  left_join(x=.,
            y=teams %>% select(team_abbr, away_nick = team_nick),
            by=c('away_team' = 'team_abbr')) %>% 
  mutate(down_dist = paste(down, ydstogo, sep = '-'),
         score = paste(total_away_score, total_home_score, sep = '-'), 
         play_type = case_when(play_type == 'pass' ~ 'Pass',
                               play_type == 'run' ~ 'Run',
                               play_type == 'field_goal' ~ 'FG',
                               play_type == 'punt' ~ 'Punt',
                               TRUE ~ 'Other'),
         abs_epa = abs(epa),
         wp_post_play = wp + wpa) %>% 
  group_by(game_id) %>% 
  arrange(-abs_epa) %>%
  select(game_id, week, home_nick, away_nick, team_wordmark, qtr, time, down_dist, yrdln, score, play_type,
         desc, epa, wp, wp_post_play) %>%
  # filtering out garbage time (Congelio book recommends using 95/5 split if you're going to remove garbage time at all)
  filter(wp > .05 & wp < .95) %>% 
  slice(1:10) %>% 
  ungroup()
```

```{r}
top_plays %>% 
  distinct(game_id)
```

```{r top_plays_params, include=TRUE}
# choose the game
game_id_param <- '2025_01_PIT_NYJ'

week_param <- top_plays %>% 
  filter(game_id == game_id_param) %>% 
  slice(1) %>% 
  pull(week)

home_team_param <- top_plays %>% 
  filter(game_id == game_id_param) %>% 
  slice(1) %>% 
  pull(home_nick)

away_team_param <- top_plays %>% 
  filter(game_id == game_id_param) %>% 
  slice(1) %>% 
  pull(away_nick)
```

```{r gt_top_plays, include=TRUE}
top_plays %>% 
  filter(game_id == game_id_param) %>% 
  select(-game_id) %>% 
  gt() %>% 
  gt_img_rows(columns = team_wordmark) %>% 
  #rename columns
  cols_label(team_wordmark = 'Possessing team',
             qtr = 'Qtr',
             time = 'Time',
             down_dist = 'Down-Dist',
             yrdln = 'Field Pos',
             play_type = 'Play',
             desc = 'Description',
             # ydsnet = 'Yards',
             wp = 'Win Prob (pre-play)',
             wp_post_play = 'Win Prob (post-play)') %>% 
  #add table title
  tab_header(
    title = md(glue("Top plays from the {home_team_param} vs {away_team_param}<br>Week {week_param} Matchup")),
    # title = md("**Biggest Plays of the Game**"),
    subtitle = md("Plays ranked by absolute value of Expected Points Added<br>Excluding garbage time where win probabilty is .05 < x < .95")) %>% 
  tab_source_note(source_note = 'Replicating work done by Kevin Cole in the Unexpected Points Substack newsletter') %>% 
  fmt_number(columns = epa,
             decimals = 2) %>% 
  fmt_percent(columns = c(wp, wp_post_play),
              decimals = 1) %>% 
  #apply new style to all column headers
  tab_style(
    locations = cells_column_labels(columns = everything()),
    style = list(
      #thick border
      cell_borders(sides = "bottom", weight = px(3)),
      #make text bold
      cell_text(weight = "bold")
    )
  ) %>% 
  #apply different style to title
  tab_style(locations = cells_title(groups = "title"),
            style = list(
              cell_text(weight = "bold", size = 24)
            )) %>% 
  data_color(
    columns = epa,
    fn = scales::col_numeric(
      palette = c("red", "white", "darkgreen"),
      domain = c(min_epa, max_epa)
    )) %>%
  gt_theme_athletic() %>%
  tab_options(
    #remove border between column headers and title
    # column_labels.border.top.width = px(5),
    # column_labels.border.top.color = "transparent",
    # #remove border around the table
    # table.border.top.color = "transparent",
    # table.border.bottom.color = "transparent",
    # #adjust font sizes and alignment
    # heading.title.font.size = px(60),
    # heading.subtitle.font.size = px(16),
    table.font.size = px(14),
    # source_notes.font.size = px(12),
    heading.align = "center"
  )
  # gtsave('.//output/test.html')
```

```{r}
play_by_play_2025 %>% 
  filter(game_id == '2025_01_PIT_NYJ',
         play_type %in% c('run', 'pass')) %>% 
  group_by(posteam, play_type) %>% 
  summarise(success_rate = round(100*mean(success[!is.na(down)], na.rm = TRUE), 1),
            avg_epa = round(mean(epa[penalty == 0], na.rm = TRUE), 2),
            .groups = 'drop') %>% 
  pivot_wider(names_from = play_type, values_from = success_rate:avg_epa)
```

```{r}
play_by_play_2025 %>% 
  filter(game_id == '2025_01_PIT_NYJ',
         play_type %in% c('run', 'pass')) %>% 
  group_by(posteam) %>% 
  summarise(success_rate = round(100*mean(success, na.rm = TRUE), 1),
            avg_epa = round(mean(epa, na.rm = TRUE), 2),
            .groups = 'drop')
```

```{r}
play_by_play_2024 %>% 
  filter(game_id == '2025_01_PIT_NYJ',
         !is.na(posteam)) %>% 
  # select(success, everything())
  group_by(posteam, home_team) %>% 
  summarise(success_rate = mean(success[!is.na(down)], na.rm = TRUE), 
            epa_turnover = sum(epa[interception == 1 | fumble_lost == 1], na.rm = TRUE),
            epa_3rd_4th = sum(epa[down == 3 | down == 4 & penalty == 0], na.rm = TRUE),
            epa_special_penalties = sum(epa[special == 1 | penalty == 1], na.rm = TRUE))
  pivot_wider(names_from = posteam, values_from = epa_turnover:epa_special_penalties) %>% 
  # need to come up with a better way to do this part
  mutate(epa_turnover_diff = epa_turnover_PIT - epa_turnover_NYG,
         # this one isn't matching...
         epa_3rd_4th_diff = epa_3rd_4th_PIT - epa_3rd_4th_NYG,
         epa_special_penalties_diff = epa_special_penalties_PIT - epa_special_penalties_NYG) %>% 
  select(home_team, contains('diff'), everything())

            
```


# Exploring summary statistics and totals using PFR stats

```{r get_pfr_data, include=TRUE}
pfr_stats_pass <- nflreadr::load_pfr_advstats(seasons = 2025,
                                              stat_type = 'pass',
                                              summary_level = "week") %>%
  left_join(x=.,
            y=player_ids,
            by='pfr_player_id')

pfr_stats_rec <- nflreadr::load_pfr_advstats(seasons = 2025,
                                              stat_type = 'rec',
                                              summary_level = "week") %>%
  left_join(x=.,
            y=player_ids,
            by='pfr_player_id')


pfr_stats_rush <- nflreadr::load_pfr_advstats(seasons = 2025,
                                              stat_type = 'rush',
                                              summary_level = "week") %>%
  left_join(x=.,
            y=player_ids,
            by='pfr_player_id')
```

```{r}
play_by_play_2025 %>% 
  filter(posteam == 'PIT',
         !is.na(receiver_player_name)) %>% 
  group_by(game_id, posteam, receiver_player_id, receiver_player_name) %>%
  summarise(epa = sum(epa, na.rm = TRUE),
            count_targets = n(),
            catches = sum(complete_pass, na.rm = TRUE), 
            touchdowns = sum(touchdown, na.rm = TRUE),
            yards_receiving = sum(receiving_yards, na.rm = TRUE), 
            # long = if_else(is.infinite(max(receiving_yards, na.rm = TRUE)),
            #                   0,
            #                   max(receiving_yards, na.rm = TRUE)),
            first_down_catch = sum(first_down_pass, na.rm = TRUE), 
            .groups = 'drop') %>% 
  mutate(epa_per_target = epa / count_targets,
         yards_per_catch = if_else(yards_receiving == 0, 0, round(yards_receiving / catches, 1))) %>% 
  left_join(x=.,
            y=pfr_stats_rec %>% select(game_id, player_id, contains('receiving')),
            by=c('game_id' = 'game_id', 'receiver_player_id' = 'player_id')) %>% 
  # filter(game_id == '2024_07_NYJ_PIT') %>% 
  arrange(-epa)
```

```{r}
play_by_play_2025 %>% 
  filter(posteam == 'PIT',
         !is.na(passer),
         play_type == 'pass') %>% 
  # select(contains('complet'))
  # filter(game_id == '2024_07_NYJ_PIT')
  # select(contains('epa'))
  group_by(game_id, posteam, passer_player_id, passer) %>%
  # group_by(posteam, passer) %>% 
  summarise(epa = sum(epa, na.rm = TRUE),
            air_epa = sum(air_epa, na.rm = TRUE),
            yac_epa = sum(yac_epa, na.rm = TRUE),
            qb_epa = sum(qb_epa, na.rm = TRUE),
            xyac_epa = sum(xyac_epa, na.rm = TRUE),
            attempts = n(),
            completions = sum(complete_pass, na.rm = TRUE), 
            touchdowns = sum(touchdown, na.rm = TRUE),
            incomplete_pass = sum(incomplete_pass, na.rm = TRUE),
            complete_pass = sum(complete_pass, na.rm = TRUE), 
            sacks = sum(sack, na.rm = TRUE),
            # sack_yards = if_else(sack == 1, sum(yards_gained, na.rm = TRUE), 0),
            # yards_receiving = sum(receiving_yards, na.rm = TRUE), 
            # long = ifelse(is.infinite(max(receiving_yards, na.rm = TRUE)),
            #                   0,
            #                   max(receiving_yards, na.rm = TRUE)),
            # first_down_catch = sum(first_down_pass, na.rm = TRUE), 
            .groups = 'drop') %>% 
  mutate(attempts = incomplete_pass + complete_pass) %>% 
         # yards_per_catch = if_else(yards_receiving == 0, 0, round(yards_receiving / catches, 1))) %>% 
  left_join(x=.,
            y=pfr_stats_pass,
            by=c('game_id' = 'game_id', 'passer_player_id' = 'player_id')) %>% 
  # filter(game_id == '2024_07_NYJ_PIT') %>% 
  arrange(-epa)
```


```{r}
dictionary_pfr_passing
```